name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Run a multi-line script
      env:  
        codescan_org: ci-tests
        codescan_project_key: gitlab-ci
        codescan_token: ${{ secrets.codescan_token }}
      run: |
        # By default, the CLI periodically checks for and installs updates.
        # Disable (false) this auto-update check to improve performance of CLI commands.
        export SFDX_AUTOUPDATE_DISABLE=false

        # Set to true if you want to use the generic UNIX keychain instead of the Linux libsecret library or macOS keychain.
        # Specify this variable when using the CLI with ssh or "headless" in a CI environment.
        export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true

        # Specifies the time, in seconds, that the CLI waits for the Lightning Experience custom domain to resolve and become available in a newly-created scratch org.
        # If you get errors about My Domain not configured when you try to use a newly-created scratch org, increase this wait time.
        export SFDX_DOMAIN_RETRY=300

        # For force:package:create, disables automatic updates to the sfdx-project.json file.
        export SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_CREATE=true

        # For force:package:version:create, disables automatic updates to the sfdx-project.json file.
        export SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE=true

        wget -q https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
        ./sfdx/install
        export PATH=./sfdx/$(pwd):$PATH

        # Output CLI version and plug-in information
        sfdx update
        sfdx --version
        sfdx plugins --core
 
        # Install the CodeScan plugin using the Salesforce CLI
        # The echo is to accept that the plugin is unsigned.
        echo y|sfdx plugins:install sfdx-codescan-plugin
        # Output the plug-in information
        sfdx plugins

        sfdx codescan:run --token $codescan_token --projectkey $codescan_project_key --organization $codescan_org
