name: CI

on: [push]

jobs:
  build:

    runs-on: frekele/ant 

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        java -version
        ant -version
